name: playground
description: Dart Playground
version: 0.0.1
# repository: https://github.com/vpetreski/playground.dart

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
